apiVersion: v1
kind: Service
metadata:
  name: myapp-service  # Change to your service name
  labels:
    app: myapp         # Change to match your deployment labels
spec:
  type: LoadBalancer    # Use NodePort if you prefer
  selector:
    app: myapp          # This should match the labels in your deployment
  ports:
    - port: 8080          # Port exposed by the service
      targetPort: 8080  # Port on the pod where the app is running
